ingress:
  host: buildmystudy.com
  pathType: Prefix

service:
  port: 80

spring:
  labels: response
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/surveypulse/advertise   # ECR에 저장된 스프링 이미지 URL
    tag: latest
  service:
    port: 80
    response:
      name: response-service
      port: 8084
  datasource:
    url: ""
    username: ""
    password: ""
