server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: response-service
  datasource:
    url: jdbc:mysql://surveypulse-rds.c9s06ug8a482.ap-northeast-2.rds.amazonaws.com:3306/response_service?serverTimezone=UTC
    username: admin
    password: asdf2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: boot-pgudwjf2.c1.kafka-serverless.ap-northeast-2.amazonaws.com:9098
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

  jpa:
    hibernate:
      ddl-auto: update  # 첫 배포 시 'create', 그 후에는 'update' 권장
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      mode: never

  jwt:
    issuer: dsada
    secret: your-very-strong-secret-key-which-is-at-least-32-characters-long

logging:
  level:
    com.example.response_service.client: DEBUG
    feign.Logger: DEBUG

feign:
  survey-service-url: http://localhost:8083
  user-service-url: http://localhost:8081
  report-service-url: http://localhost:8085

resilience4j.circuitbreaker:
  instances:
    userService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
    surveyService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 10s